name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: '${{github.sha}}' 
  GITHUB_REF: '${{github.ref}}'
  IMAGE: 'python:3.7.13-slim'
  REGISTRY_HOSTNAME: 'gcr.io'
  IMAGE_NAME: 'flask-helloworld'
  PROJECT_NAME: 'helloworld_370205'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # 在 $GITHUB_WORKSPACE 下簽出您的存儲庫，以便您的工作可以訪問它
      - uses: actions/checkout@v2
      # 在 Runner 上使用 shell 顯示出 Hello world
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Make 9527
        id: iam_9527
        run: echo "SELECTED_MAN=ha9527" >> $GITHUB_OUTPUT
      - name: Get 9527
        run: echo "The selected man is ${{ steps.iam_9527.outputs.SELECTED_MAN }}"      

      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow.$IMAGE" >> $GITHUB_ENV
          
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
